param(
  [string]$InstallRoot = "",
  [switch]$Force,
  [switch]$SkipSdkInstall
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Official sources:
# - Eclipse Adoptium API resolves the latest Temurin/OpenJDK 17 GA Windows x64 JDK.
# - Android command-line tools URL is from https://developer.android.com/studio#command-line-tools-only.
# - Gradle distributions are published at https://services.gradle.org/distributions/.
$JdkUrl = "https://api.adoptium.net/v3/binary/latest/17/ga/windows/x64/jdk/hotspot/normal/eclipse"
$AndroidCommandLineToolsUrl = "https://dl.google.com/android/repository/commandlinetools-win-14742923_latest.zip"
$GradleVersion = "8.13"
$GradleUrl = "https://services.gradle.org/distributions/gradle-$GradleVersion-bin.zip"

$RepoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
if ([string]::IsNullOrWhiteSpace($InstallRoot)) {
  $InstallRoot = "D:\android-dev"
} elseif (-not [System.IO.Path]::IsPathRooted($InstallRoot)) {
  $InstallRoot = Join-Path $RepoRoot $InstallRoot
}

$InstallRoot = [System.IO.Path]::GetFullPath($InstallRoot)
$DownloadDir = Join-Path $InstallRoot "downloads"
$JdkRoot = Join-Path $InstallRoot "jdk"
$AndroidHome = Join-Path $InstallRoot "android-sdk"
$CommandLineToolsLatestDir = Join-Path $AndroidHome "cmdline-tools\latest"
$CommandLineToolsStagingDir = Join-Path $InstallRoot "staging\android-commandlinetools"
$GradleRoot = Join-Path $InstallRoot "gradle"
$LocalPropertiesPath = Join-Path $RepoRoot "android\local.properties"

function Write-Step {
  param([string]$Message)
  Write-Host "[setup:android-dev] $Message"
}

function Ensure-Directory {
  param([string]$PathValue)
  New-Item -ItemType Directory -Path $PathValue -Force | Out-Null
}

function Save-UrlIfNeeded {
  param(
    [string]$Url,
    [string]$OutFile,
    [string]$Label
  )

  if ((Test-Path -LiteralPath $OutFile) -and (-not $Force)) {
    Write-Step "$Label archive already exists, skipping download: $OutFile"
    return
  }

  Ensure-Directory -PathValue ([System.IO.Path]::GetDirectoryName($OutFile))
  Write-Step "Downloading $Label from $Url"
  try {
    Invoke-WebRequest -Uri $Url -OutFile $OutFile
  } catch {
    throw "Failed to download $Label. Check network access or pass a different -InstallRoot after downloading manually. $($_.Exception.Message)"
  }
}

function Expand-ArchiveIfNeeded {
  param(
    [string]$ArchivePath,
    [string]$DestinationDir,
    [string]$ProbePath,
    [string]$Label
  )

  if ((Test-Path -LiteralPath $ProbePath) -and (-not $Force)) {
    Write-Step "$Label is already expanded, skipping: $ProbePath"
    return
  }

  Ensure-Directory -PathValue $DestinationDir
  Write-Step "Expanding $Label into $DestinationDir"
  Expand-Archive -LiteralPath $ArchivePath -DestinationPath $DestinationDir -Force
}

function Find-JavaHome {
  param([string]$SearchRoot)

  if (-not (Test-Path -LiteralPath $SearchRoot)) {
    return $null
  }

  $java = Get-ChildItem -LiteralPath $SearchRoot -Filter "java.exe" -File -Recurse |
    Where-Object { $_.FullName -match "\\bin\\java\.exe$" } |
    Sort-Object FullName |
    Select-Object -First 1

  if (-not $java) {
    return $null
  }

  return (Split-Path -Parent (Split-Path -Parent $java.FullName))
}

function Find-GradleHome {
  param([string]$SearchRoot)

  if (-not (Test-Path -LiteralPath $SearchRoot)) {
    return $null
  }

  $gradle = Get-ChildItem -LiteralPath $SearchRoot -Filter "gradle.bat" -File -Recurse |
    Where-Object { $_.FullName -match "\\bin\\gradle\.bat$" } |
    Sort-Object FullName |
    Select-Object -First 1

  if (-not $gradle) {
    return $null
  }

  return (Split-Path -Parent (Split-Path -Parent $gradle.FullName))
}

function Add-PathEntry {
  param([string]$PathValue)

  if (-not (Test-Path -LiteralPath $PathValue)) {
    return
  }

  $currentParts = @()
  if (-not [string]::IsNullOrWhiteSpace($env:PATH)) {
    $currentParts = $env:PATH -split [System.IO.Path]::PathSeparator
  }

  $alreadyPresent = $false
  foreach ($part in $currentParts) {
    if ($part -ieq $PathValue) {
      $alreadyPresent = $true
      break
    }
  }

  if (-not $alreadyPresent) {
    $env:PATH = $PathValue + [System.IO.Path]::PathSeparator + $env:PATH
  }
}

function Write-LocalProperties {
  param([string]$SdkDir)

  $androidDir = Split-Path -Parent $LocalPropertiesPath
  if (-not (Test-Path -LiteralPath $androidDir)) {
    throw "Android project directory was not found: $androidDir"
  }

  $sdkDirForProperties = $SdkDir -replace "\\", "/"
  $content = @(
    "# Generated by scripts/setupAndroidDevEnv.ps1.",
    "# This file is local machine state and should not be committed.",
    "sdk.dir=$sdkDirForProperties"
  )

  Set-Content -LiteralPath $LocalPropertiesPath -Value $content -Encoding UTF8
  Write-Step "Wrote Android SDK path to $LocalPropertiesPath"
}

function Invoke-SdkManager {
  param(
    [string[]]$Arguments,
    [string[]]$InputLines = @()
  )

  $sdkManager = Join-Path $CommandLineToolsLatestDir "bin\sdkmanager.bat"
  if (-not (Test-Path -LiteralPath $sdkManager)) {
    throw "sdkmanager was not found: $sdkManager"
  }

  if ($InputLines.Count -gt 0) {
    $InputLines | & $sdkManager @Arguments
  } else {
    & $sdkManager @Arguments
  }

  if ($LASTEXITCODE -ne 0) {
    throw "sdkmanager failed with exit code ${LASTEXITCODE}: $($Arguments -join ' ')"
  }
}

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Ensure-Directory -PathValue $InstallRoot
Ensure-Directory -PathValue $DownloadDir
Ensure-Directory -PathValue $AndroidHome

$JdkZip = Join-Path $DownloadDir "temurin-openjdk-17-windows-x64.zip"
$existingJavaHome = Find-JavaHome -SearchRoot $JdkRoot
if ($existingJavaHome -and (-not $Force)) {
  Write-Step "Temurin/OpenJDK 17 appears installed, skipping: $existingJavaHome"
} else {
  Save-UrlIfNeeded -Url $JdkUrl -OutFile $JdkZip -Label "Temurin/OpenJDK 17"
  Expand-ArchiveIfNeeded -ArchivePath $JdkZip -DestinationDir $JdkRoot -ProbePath (Join-Path $JdkRoot "*\bin\java.exe") -Label "Temurin/OpenJDK 17"
}

$JavaHome = Find-JavaHome -SearchRoot $JdkRoot
if (-not $JavaHome) {
  throw "Could not locate java.exe after JDK setup under $JdkRoot"
}

$AndroidToolsZip = Join-Path $DownloadDir "commandlinetools-win-14742923_latest.zip"
$sdkManagerPath = Join-Path $CommandLineToolsLatestDir "bin\sdkmanager.bat"
if ((Test-Path -LiteralPath $sdkManagerPath) -and (-not $Force)) {
  Write-Step "Android command-line tools already installed, skipping: $sdkManagerPath"
} else {
  Save-UrlIfNeeded -Url $AndroidCommandLineToolsUrl -OutFile $AndroidToolsZip -Label "Android command-line tools"
  Expand-ArchiveIfNeeded -ArchivePath $AndroidToolsZip -DestinationDir $CommandLineToolsStagingDir -ProbePath (Join-Path $CommandLineToolsStagingDir "cmdline-tools\bin\sdkmanager.bat") -Label "Android command-line tools"

  $stagedToolsDir = Join-Path $CommandLineToolsStagingDir "cmdline-tools"
  if (-not (Test-Path -LiteralPath (Join-Path $stagedToolsDir "bin\sdkmanager.bat"))) {
    throw "Expanded Android command-line tools did not contain cmdline-tools\bin\sdkmanager.bat"
  }

  Ensure-Directory -PathValue $CommandLineToolsLatestDir
  Write-Step "Copying Android command-line tools into $CommandLineToolsLatestDir"
  Get-ChildItem -LiteralPath $stagedToolsDir -Force |
    Copy-Item -Destination $CommandLineToolsLatestDir -Recurse -Force
}

$GradleZip = Join-Path $DownloadDir "gradle-$GradleVersion-bin.zip"
$existingGradleHome = Find-GradleHome -SearchRoot $GradleRoot
if ($existingGradleHome -and (-not $Force)) {
  Write-Step "Gradle appears installed, skipping: $existingGradleHome"
} else {
  Save-UrlIfNeeded -Url $GradleUrl -OutFile $GradleZip -Label "Gradle $GradleVersion"
  Expand-ArchiveIfNeeded -ArchivePath $GradleZip -DestinationDir $GradleRoot -ProbePath (Join-Path $GradleRoot "gradle-$GradleVersion\bin\gradle.bat") -Label "Gradle $GradleVersion"
}

$GradleHome = Find-GradleHome -SearchRoot $GradleRoot
if (-not $GradleHome) {
  throw "Could not locate gradle.bat after Gradle setup under $GradleRoot"
}

$env:JAVA_HOME = $JavaHome
$env:ANDROID_HOME = $AndroidHome
$env:ANDROID_SDK_ROOT = $AndroidHome
Add-PathEntry -PathValue (Join-Path $JavaHome "bin")
Add-PathEntry -PathValue (Join-Path $CommandLineToolsLatestDir "bin")
Add-PathEntry -PathValue (Join-Path $AndroidHome "platform-tools")
Add-PathEntry -PathValue (Join-Path $GradleHome "bin")

if ($SkipSdkInstall) {
  Write-Step "Skipping SDK package install because -SkipSdkInstall was set."
} else {
  Write-Step "Accepting Android SDK licenses"
  $licenseAnswers = 1..100 | ForEach-Object { "y" }
  Invoke-SdkManager -Arguments @("--sdk_root=$AndroidHome", "--licenses") -InputLines $licenseAnswers

  Write-Step "Installing Android SDK packages: platforms;android-35, build-tools;34.0.0, build-tools;35.0.0, platform-tools"
  Invoke-SdkManager -Arguments @(
    "--sdk_root=$AndroidHome",
    "platforms;android-35",
    "build-tools;34.0.0",
    "build-tools;35.0.0",
    "platform-tools"
  )
}

Write-LocalProperties -SdkDir $AndroidHome

Write-Host ""
Write-Step "Android development environment is ready for this PowerShell session."
Write-Host "Run these commands in a new shell to reuse the same local toolchain:"
Write-Host "`$env:JAVA_HOME = `"$JavaHome`""
Write-Host "`$env:ANDROID_HOME = `"$AndroidHome`""
Write-Host "`$env:ANDROID_SDK_ROOT = `"$AndroidHome`""
Write-Host "`$env:PATH = `"$((Join-Path $JavaHome "bin"));$((Join-Path $CommandLineToolsLatestDir "bin"));$((Join-Path $AndroidHome "platform-tools"));$((Join-Path $GradleHome "bin"));`$env:PATH`""
Write-Host ""
Write-Host "Installed roots:"
Write-Host "  JAVA_HOME=$JavaHome"
Write-Host "  ANDROID_HOME=$AndroidHome"
Write-Host "  GRADLE_HOME=$GradleHome"
