package com.firstaid.copilot.live

data class DemoPreset(
    val id: String,
    val label: String,
    val summary: String,
    val eventSource: String? = null,
    val eventType: String? = null,
    val patientState: Map<String, Any?>? = null,
    val cprQuality: Map<String, Any?>? = null,
    val rescuerState: Map<String, Any?>? = null,
    val deviceState: Map<String, Any?>? = null,
    val metadata: Map<String, Any?>? = null,
    val toolResult: Map<String, Any?>? = null,
    val requiresCprLoop: Boolean = false,
    val requiresCprSetup: Boolean = false,
    val bestAfterCprSetup: Boolean = false,
)

data class DemoTurn(
    val preset: DemoPreset,
    val text: String? = null,
)

fun demoPresetById(id: String): DemoPreset =
    demoPresets.first { it.id == id }

fun demoCprSetupSequence(): List<DemoTurn> = listOf(
    DemoTurn(demoPresetById("scene_safe"), "现场安全了"),
    DemoTurn(demoPresetById("unresponsive"), "他没有反应"),
    DemoTurn(demoPresetById("no_breathing"), "没有正常呼吸"),
    DemoTurn(demoPresetById("call_started"), "120 已经拨打"),
    DemoTurn(demoPresetById("cpr_ready"), "准备好了"),
    DemoTurn(demoPresetById("cpr_start"), "开始按压"),
)

val demoPresets: List<DemoPreset> = listOf(
    DemoPreset(
        id = "none",
        label = "No mock",
        summary = "voice / text only",
    ),
    DemoPreset(
        id = "scene_safe",
        label = "Scene safe",
        summary = "vision_patient: scene_safe=true",
        eventSource = "vision_patient",
        eventType = "patient_state_update",
        patientState = mapOf(
            "adult_likely" to true,
            "lying_down" to true,
            "responsive" to null,
            "normal_breathing" to null,
            "agonal_breathing" to null,
            "chest_movement" to "unknown",
            "confidence" to 0.86,
        ),
        metadata = mapOf("scene_safe" to true, "scene_note" to "mock_scene_safe"),
    ),
    DemoPreset(
        id = "unresponsive",
        label = "No response",
        summary = "vision_patient: responsive=false",
        eventSource = "vision_patient",
        eventType = "patient_state_update",
        patientState = mapOf(
            "adult_likely" to true,
            "lying_down" to true,
            "responsive" to false,
            "normal_breathing" to null,
            "agonal_breathing" to null,
            "chest_movement" to "unknown",
            "confidence" to 0.91,
        ),
        metadata = mapOf("scene_note" to "mock_unresponsive"),
    ),
    DemoPreset(
        id = "no_breathing",
        label = "No normal breathing",
        summary = "vision_patient: normal_breathing=false",
        eventSource = "vision_patient",
        eventType = "breathing_update",
        patientState = mapOf(
            "adult_likely" to true,
            "lying_down" to true,
            "responsive" to false,
            "normal_breathing" to false,
            "agonal_breathing" to true,
            "chest_movement" to "irregular",
            "confidence" to 0.9,
        ),
        metadata = mapOf("scene_note" to "mock_no_normal_breathing"),
    ),
    DemoPreset(
        id = "call_started",
        label = "120 started",
        summary = "device: emergency_call_started=true",
        eventSource = "device",
        eventType = "device_state_update",
        deviceState = mapOf(
            "emergency_call_started" to true,
            "emergency_call_status" to "started",
            "gps_attached" to true,
            "recording" to true,
            "network" to "offline",
        ),
        metadata = mapOf("scene_note" to "mock_call_started"),
    ),
    DemoPreset(
        id = "cpr_ready",
        label = "CPR ready",
        summary = "需先完成安全、反应、呼吸和 120：vision_patient ready for compressions",
        eventSource = "vision_patient",
        eventType = "patient_state_update",
        patientState = mapOf(
            "adult_likely" to true,
            "lying_down" to true,
            "responsive" to false,
            "normal_breathing" to false,
            "agonal_breathing" to true,
            "chest_movement" to "irregular",
            "confidence" to 0.89,
        ),
        metadata = mapOf("scene_note" to "mock_cpr_ready"),
        requiresCprSetup = true,
    ),
    DemoPreset(
        id = "cpr_start",
        label = "CPR started",
        summary = "需先进入 CPR：vision_cpr quality_score=35",
        eventSource = "vision_cpr",
        eventType = "cpr_quality_update",
        cprQuality = cprQuality(100, 100, 35, "center", "straight", 0, 10, true),
        requiresCprSetup = true,
    ),
    DemoPreset(
        id = "hand_left",
        label = "Hand left",
        summary = "仅 CPR 中有效：vision_cpr hand_position=left",
        eventSource = "vision_cpr",
        eventType = "cpr_quality_update",
        cprQuality = cprQuality(110, 105, 42, "left", "straight", 0, 40, true),
        requiresCprLoop = true,
    ),
    DemoPreset(
        id = "rate_low",
        label = "Rate low",
        summary = "仅 CPR 中有效：vision_cpr current_rate=82",
        eventSource = "vision_cpr",
        eventType = "cpr_quality_update",
        cprQuality = cprQuality(82, 95, 50, "center", "straight", 0, 70, true),
        requiresCprLoop = true,
    ),
    DemoPreset(
        id = "arm_bent",
        label = "Arm bent",
        summary = "仅 CPR 中有效：vision_cpr arm_posture=bent",
        eventSource = "vision_cpr",
        eventType = "cpr_quality_update",
        cprQuality = cprQuality(112, 102, 58, "center", "bent", 0, 100, true),
        requiresCprLoop = true,
    ),
    DemoPreset(
        id = "interrupted",
        label = "Interrupted",
        summary = "仅 CPR 中有效：vision_cpr interruption_seconds=4",
        eventSource = "vision_cpr",
        eventType = "cpr_quality_update",
        cprQuality = cprQuality(0, 100, 55, "center", "straight", 4, 120, false),
        requiresCprLoop = true,
    ),
    DemoPreset(
        id = "quality_good",
        label = "Quality good",
        summary = "仅 CPR 中有效：vision_cpr quality_score=90",
        eventSource = "vision_cpr",
        eventType = "cpr_quality_update",
        cprQuality = cprQuality(110, 109, 90, "center", "straight", 0, 240, true),
        requiresCprLoop = true,
    ),
    DemoPreset(
        id = "fatigue",
        label = "Rescuer fatigue",
        summary = "仅 CPR 中有效：vision_rescuer fatigue_level=high",
        eventSource = "vision_rescuer",
        eventType = "rescuer_state_update",
        rescuerState = mapOf(
            "emotion" to "anxious",
            "fatigue_level" to "high",
            "hesitation_seconds" to 0,
            "confidence" to 0.8,
        ),
        requiresCprLoop = true,
    ),
    DemoPreset(
        id = "aed_arrived",
        label = "AED arrived",
        summary = "CPR 中的视觉 AED 到达事件：会进入 S8_ASSISTANCE，TTS 应继续按压并听设备提示",
        eventSource = "vision_patient",
        eventType = "patient_state_update",
        metadata = mapOf(
            "aed_available" to true,
            "helper_arrived" to true,
            "scene_note" to "mock_aed_arrived",
        ),
        bestAfterCprSetup = true,
    ),
    DemoPreset(
        id = "ems_arrived",
        label = "EMS arrived",
        summary = "vision_patient: handover_requested",
        eventSource = "vision_patient",
        eventType = "handover_requested",
        metadata = mapOf("ems_arrived" to true, "scene_note" to "mock_ems_arrived"),
    ),
    DemoPreset(
        id = "report_ready",
        label = "Report ready",
        summary = "device: handover_report_generated=true",
        eventSource = "device",
        eventType = "tool_result",
        metadata = mapOf(
            "handover_report_generated" to true,
            "local_video_saved" to true,
            "scene_note" to "mock_report_ready",
        ),
        toolResult = mapOf("type" to "generate_handover_report", "status" to "ok"),
    ),
)

private fun cprQuality(
    currentRate: Int,
    averageRate: Int,
    qualityScore: Int,
    handPosition: String,
    armPosture: String,
    interruptionSeconds: Int,
    totalCompressions: Int,
    compressionsStarted: Boolean,
): Map<String, Any?> =
    mapOf(
        "compressions_started" to compressionsStarted,
        "current_rate" to currentRate,
        "average_rate" to averageRate,
        "quality_score" to qualityScore,
        "hand_position" to handPosition,
        "arm_posture" to armPosture,
        "interruption_seconds" to interruptionSeconds,
        "total_compressions" to totalCompressions,
    )
